### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by mkruckow** [POSYDON-code/POSYDON-public#133]
When I try to `import posydon.interpolation.profile_interpolation` I get the following error:
```
File ~/POSYDON/posydon/interpolation/profile_interpolation.py:18
     16 import numpy as np
     17 import pandas as pd
---> 18 import tensorflow as tf
     19 tf.get_logger().setLevel('ERROR')
     20 from tensorflow.keras import layers, losses, models, optimizers

ModuleNotFoundError: No module named 'tensorflow'
```
I guess, we didn't added the `tensorflow` module to your installation requests. Hence, we should add it there.

**Comment by elizabethteng** [comment]
Hi @mkruckow, we added tensorflow to the extras_require in setup.py. I'm guessing you didn't explicitly include it in your install? Do you recommend that we add it to the necessary packages?

**Comment by mkruckow** [comment]
Ah I see. One would need to install it separately. I'm not sure whether it is a good idea to include it in the repo, while it is not working, when doing the normal installation of the repo.
Hence, I'd wonder whether things like this should then more be submodules and not part of the repo.
In case we'd like to keep it in the repo, I'd suggest to put a check there. And give the user the info how to install it: it won't be obvious to a user to get it via `pip install .[profile]`.
Btw. after installing it in this way, I get a warning from the tensorflow module `W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT`. Is this expected? Or does it point towards something more to be missing?

**Comment by astroJeff** [comment]
According to @elizabethteng, the `Could not find TensorRT` warning is from GPU acceleration, so the code should still run just fine.

We fixed this issue as a TEAM in a dev call. This should be resolved now.
