### ISSUE TITLE
Removing MPI dependency to run population synthesis models

### ISSUE THREAD

**Issue by ssbvr** [POSYDON-code/POSYDON-public#156]
Currently, one would be required to use MPI to run large population synthesis models; see `docs/_source/tutorials-examples/population-synthesis/pop_syn.ipynb` tutorial. The population synthesis model will start only when all resources are available simultaneously, which rarely happens on a public HPC queue. To solve this problem, the population synthesis model should evolve each model batch in a slurm job array asynchronously and have a job at the end of the array to combine all batch files into the final population objects.

This change is important and should be done before the v2.0.0 software release to facilitate new users to run POSYDON population synthesis models on smaller HPC facilities than what we have available within the collaboration.

**Comment by maxbriel** [comment]
This is now implemented with PR #175 .
