### ISSUE TITLE
Underlying stellar mass in `SyntheticPopulation`

### ISSUE THREAD

**Issue by ssbvr** [POSYDON-code/POSYDON-public#168]
I believe we merged or will merge a PR from @ezapartas and @kasdaglie, allowing us to support a mixture of single and binary stars in a single population. Somone should verify that after this is done, the renormalization of the IMF with the @devimisra method I implemented in the `SyntheticPopulation` class is still correct. When we parse the population synthesis output, we compute the total simulated mass, which we rescale to obtain the total underlying stellar mass for a given metallicity when computing the Synthetic Population data frame of the `SyntheicPopulation` class. This calculation assumes that the simulated mass is only of binary stars and takes a binary fraction for the renormalization like in Appendix A of `Bavera+20`. After the change, you will have single stars in the binary populations. Hence the renormalization will be wrong. Alternatively, suppose the user only simulates binaries setting `binary_fraction=1`. In that case, the simulated mass will not be rescaled correctly as the method reads the binary fraction from the ini file, which in this case, in 1 when it should be, say 0.7 or 0.5.

**Comment by mkruckow** [comment]
It is not only the binary fraction which is important for the underlying mass.
Currently the calculation of the underlying mass assumes certain distributions and ranges of them to calculate those. This becomes especially problematic, if one wants to study a population, which is (partly) outside the assumed bounds.
Additionally, we don't take all initial distributions into account to get rates for populations, e.g. the period.

**Comment by astroJeff** [comment]
@dimsour94 to look into and prepare a PR

**Comment by dimsour94** [comment]
Check PR#376
