### ISSUE TITLE
developement branch documentation warning about missing data

### ISSUE THREAD

**Issue by tassos25** [POSYDON-code/POSYDON-public#184]
There should be a clear warning in the v2 documentation that the necessary data to use the developement branch are not available, and hence the tutorials can not be ran if one does not have access to the still unpublished data.

**Comment by mkruckow** [comment]
This warning is there in the [installation guide](https://posydon.org/POSYDON/getting-started/installation-guide.html).
Hence, I'd suggest to only put a reminder at the tutorials that you need to get the dataset first, which links to the [installation guide at the section to download the dataset](https://posydon.org/POSYDON/getting-started/installation-guide.html#posydon-env). In this way, we only need to change one warning with publishing the dataset.

**Comment by tassos25** [comment]
Yes, but the warning is not talking about the fact that the data (both grids and data for the tutorial) are not published, so outside users cannot use the development version at all.

**Comment by mkruckow** [comment]
OK, I thought you only need the grids. And the example data should be part of the repository. If not, is there already a plan how are we providing the example data?

**Comment by maxbriel** [comment]
This was added with PR #267. I've closed the issue.
