### ISSUE TITLE
installation instructions for v1

### ISSUE THREAD

**Issue by tassos25** [POSYDON-code/POSYDON-public#185]
We should fix the headers in the installation instructions and make it clear that there are 2 options for installing posydon v1 and two options for downloading the data. Perhaps we should instead only describe one option, anaconda installation and the automatic data download.

**Comment by tassos25** [comment]
@kkovlakas Can you please have a look at it?

**Comment by kkovlakas** [comment]
> @kkovlakas Can you please have a look at it?

@tassos25 Do you mean the README of the repository, or the documentation of v.1.0?

**Comment by mkruckow** [comment]
> @tassos25 Do you mean the README of the repository, or the documentation of v.1.0?

@kkovlakas, because @tassos25 removed the instructions in the README in https://github.com/POSYDON-code/POSYDON/pull/188 and https://github.com/POSYDON-code/POSYDON/pull/189, it is clearly about the documentation of v1.

**Comment by maxbriel** [comment]
This has been implemented in PR #201.
