### ISSUE TITLE
V1 progressbar2 v4.0.0 requirement

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#190]
POSYDON V1 has a dependency on `progressbar2 v4.0.0`.
However, this package loads in `python_utils>=3.0.0` of which the newest version requires python v3.8.0.

The latest version that work with python v3.7 is python_utils v3.5.2.

This should be added as a requirement for POSYDON v1 `python_utils=3.5.2`.

**Comment by mkruckow** [comment]
Taken care of in https://github.com/POSYDON-code/POSYDON/pull/191
