### ISSUE TITLE
Population normalisation

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#192]
In `normalised_pop_mass` the binary fraction is defined in the functions as `f_bin=0.7`.

However, in the population parameters an option is present to set the `binary_fraction`. This is not currently used to normalise the population mass.
The `normalised_pop_mass` should take the given binary fraction in the population parameters.

**Comment by mkruckow** [comment]
Isn't this a duplicate of issue #168 ?

**Comment by astroJeff** [comment]
Closing - this is a duplicate of #168
