### ISSUE TITLE
Secondary star initially more massive

### ISSUE THREAD

**Issue by dimsour94** [POSYDON-code/POSYDON-public#203]
Having the default set up in my ini.file, I got this (see attached image). Secondary star initially more massive and thus when MT takes place from star 2 to star 1, it assumes RLO1 instead of RLO2. M1 initially is also lower than the primary_mass_max... Maybe the draws are ok but the definition of which star is the more massive one seems  not to work properly. @ezapartas 

![output](https://github.com/POSYDON-code/POSYDON/assets/60255936/d590d6a0-c1f8-45e2-b18d-c13c8d2c56d0)

**Comment by celiotine** [comment]
Could be related to issue #214

**Comment by mkruckow** [comment]
Should be fixed with PR #219 .
