### ISSUE TITLE
Post-processing plotting

### ISSUE THREAD

**Issue by astroJeff** [POSYDON-code/POSYDON-public#209]
I have run the post-processing script, which succeeds most of the time. In a couple cases with q>~0.85, there are a few failures. See examples below.

```
FAILED TO PLOT $q=0.85$

'case_A1/A2/A1/B1/A2'
FAILED TO PLOT $q=0.90$

'case_A1/B2/B1'
```

These should be warnings, as, at least in these specific cases, the models breaking the script are edge cases. In this case the problems is with the mass transfer strings, but there could be errors elsewhere.

Proposed solution: Define a procedure for dealing with undefined mass transfer strings.

**Comment by mkruckow** [comment]
It looks like there are more cases coming up with the new reruns.
I think, we need to stop pre defining all and failing in case there something missing. We need to get some save fall backs for the TF2.
