### ISSUE TITLE
PopSynth: SN_type defined as None

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#220]
In some cases, `CC1` or `CC2` occurs twice in the evolutionary pathway, after which the model ends, for example, `ZAMS_CC1_CC1`. This is a result of the model failing in `step_SN` due to the following error: `The SN type is not ECSN neither CCSN.`

This is a result from the interpolator in the `step_HMS_HMS` returning None for the `SN_type`, associated with the star undergoing the collapse. This is unexpected, because these stars are sufficiently massive to undergo a CC- or ECSN.
Moreover, the interpolator is predicting that this system becomes a BH.
Manually performing the collapse returns that this system should undergo a CCSN. 

The questions we would like to get clear before fixing these systems:
- Is the interpolator incorrectly predicting the SN type?
- If so, how should this be handled? Should these systems manually be recalculated? Should the interpolator be retrained?

<img width="998" alt="double CC issue" src="https://github.com/POSYDON-code/POSYDON/assets/14039563/b32e99da-68cb-4a72-a339-b036f9076cdf">

```
from posydon.binary_evol.binarystar import BinaryStar, SingleStar
from posydon.binary_evol.simulationproperties import SimulationProperties
from posydon.popsyn.io import simprop_kwargs_from_ini


sim_kwargs = simprop_kwargs_from_ini('population.ini', verbose=True)
metallicity = {'metallicity':1,}

sim_kwargs['step_HMS_HMS'][1].update(metallicity)
sim_kwargs['step_CO_HeMS'][1].update(metallicity)
sim_kwargs['step_CO_HMS_RLO'][1].update(metallicity)
sim_kwargs['step_CO_HeMS_RLO'][1].update(metallicity)
sim_kwargs['step_detached'][1].update(metallicity)
sim_kwargs['step_disrupted'][1].update(metallicity)
sim_kwargs['step_merged'][1].update(metallicity)
sim_kwargs['step_initially_single'][1].update(metallicity)

sim_pop = SimulationProperties(**sim_kwargs)

sim_pop.load_steps(verbose=True)
STAR1 = SingleStar(**{'mass': 17.782576, 
                      'state': 'H-rich_Core_H_burning'})
STAR2 = SingleStar(**{'mass':3.273864,
                      'state': 'H-rich_Core_H_burning'})

BINARY = BinaryStar(STAR1, STAR2,  
                    **{'time': 0.0, 'state': 'detached', 'event': 'ZAMS', 'orbital_period':4513.150157, 'eccentricity': 0.0},
                    properties = sim_pop)

BINARY.evolve()```

**Comment by astroJeff** [comment]
This issue appears to be fixed with PR #240, tested by @astro-abhishek. Closing.
