### ISSUE TITLE
Where do we use scikit-learn and what need to get changed?

### ISSUE THREAD

**Issue by mkruckow** [POSYDON-code/POSYDON-public#221]
I'm getting more and more often this kind of warnings:
```
*/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
*/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
```
It sounds like we are using a functionality, which won't be supported in the future. Does anyone know about, where we use this module? Finally, what do we need to change to?

**Comment by astroJeff** [comment]
@prinse1545, can you look into this?

**Comment by astroJeff** [comment]
A quick search yields a bunch of uses of scikit-learn within the classification and interpolation functionalities. Previous experience suggests to me that sklearn typically has high-quality algorithms implemented, so I'd rather fix the warnings than try to come up with solutions that don't include sklearn. 

It's a bit tough to track this one down, but we may do well just to update the scikit-learn version we are implementing.

**Comment by mkruckow** [comment]
Have you seen any place, where we call `is_sparse`?

**Comment by mkruckow** [comment]
I haven't seen it anymore recently. Hence, it looks to be solved...
