### ISSUE TITLE
ECSN condition leading to final NS mass > progenitor star mass

### ISSUE THREAD

**Issue by astro-abhishek** [POSYDON-code/POSYDON-public#244]
In some binaries like the ones shown below, the final gravitational mass of the NS turns out to be larger than its progenitor mass. The final mass of 1.260782 implies the use of the ECSN condition, which, for these binaries was the one by Podsiadlowski et al. (2004). This condition sets a proto NS mass = 1.38 in case of ECSN, which when plugged into Eq. 35 from Fragos et al. 2023, results in the calculated value of 1.260782.

It's possible that these cases are being misclassified as NS, when they actually should be WD (as in the second binary for example). If however, they are correctly classified as ECSN, could temporarily setting the proto NS mass = C/O core mass instead of the fixed value of 1.38 be a viable resolution? Additionally, there are rare cases where the SN type is 'WD', yet the final outcome is a 'NS'. This relates to an older issue from May 19, 2023.

![Screenshot 2024-01-25 at 1 21 44 AM](https://github.com/POSYDON-code/POSYDON/assets/40901312/a945fe30-608e-40f8-ba90-29f3da10cc54)

![Screenshot 2024-01-25 at 1 19 58 AM](https://github.com/POSYDON-code/POSYDON/assets/40901312/9fb3c3bb-8213-44f5-8e85-8be9ef20b773)

**Comment by maxbriel** [comment]
@astro-abhishek  would you be able to confirm if this is fixed with PR #240.

Also what is the metallicity and kick arrays of these binaries?

**Comment by astro-abhishek** [comment]
@maxbriel yes, it seems this issue was resolved with PR #240 - check the comment on that page.

Also, these particular binaries were being classified as ECSN, so they had kicks of a few 10s of km/s. These are at solar metallicity.

**Comment by astroJeff** [comment]
Closing issue, as it is addressed by PR #240
