### ISSUE TITLE
POSYDON website: DOCS link

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#245]
On posydon.org, the link to the DOCS only points to the version selection on the Home page.

On other pages, clicking on DOCS the link points to the Github.

**How to recreate:** 
1. Open the posydon.org website on a page other than Home (example: https://posydon.org/papers.html#)
2. Click on Docs.
3. It redirects to Github.

**Comment by mkruckow** [comment]
I just found this issue again, while I didn't when looking for it. I guess, it is at the wrong repository and should have been in https://github.com/POSYDON-code/POSYDON-code.github.io
There was a recent [PR#18](https://github.com/POSYDON-code/POSYDON-code.github.io/pull/18) there to fix the link on the papers page, which should have solved this issue.
If there is any remaining please reopen an issue there: https://github.com/POSYDON-code/POSYDON-code.github.io/issues
