### ISSUE TITLE
output termination catching

### ISSUE THREAD

**Issue by astroJeff** [POSYDON-code/POSYDON-public#254]
In one particular binary in the CO-HMS_RLO grid, two termination codes are printed to the standard output: one for initial RLO and another for min timestep limit. The code will default to take the last code, but in this case, it should pick up the first one. Ideally we would come up with a solution to address this.

The run is in `/projects/b1119/POSYDON_GRIDS/CO-HMS_RLO/v2/1e-02_Zsun/rerun_HeMB_MLTp_mesh_grid_low_res_no_extension/Zbase_0.0001_m1_59.4328_m2_1.1960_initial_z_1.4200e-04_initial_period_in_days_4.1753e-01_grid_index_45`

And the `out.txt` file shows:

```
termination code: Terminate because of overflowing initial model
terminated evolution: cannot find acceptable model
termination code: min_timestep_limit
```

**Comment by mkruckow** [comment]
With PR #281 we search for a second termination code in case of `min_timestep_limit`, hence the failure rates changed slightly, usually going a bit down by finding initial RLO instead of min_timestep_limit.
