### ISSUE TITLE
Binary ending in `step_merged` 

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#256]
I've noticed some binaries entering `step_merged` and just ending.
They're tagged as failing binaries, but this is not clear from the `binary.event` nor `binary.state`

Example at solar metallicity

```
STAR1 = SingleStar(**{'mass': 7.034104,
                      'state': 'H-rich_Core_H_burning'})
STAR2 = SingleStar(**{'mass': 5.852124,
                      'state': 'H-rich_Core_H_burning'})

BINARY = BinaryStar(STAR1, STAR2,  
                    **{'time': 0.0, 'state': 'detached', 'event': 'ZAMS', 'orbital_period':4.16140, 'eccentricity': 0.0},
                    properties = sim_pop)


```
<img width="1424" alt="Screenshot 2024-02-21 at 10 12 40" src="https://github.com/POSYDON-code/POSYDON/assets/14039563/0d18d877-f7ee-49e9-b49e-a46b424de999">

**Comment by maxbriel** [comment]
It looks like it always failing when a merger between a `WD` and `H-rich-Shell-H-burning` takes place. The accretion doesn't look like much before the CE is initiated.
How should this be treated?  @ezapartas do you have any suggestions?

Should the model be ended? Should we explode the WD?

**Comment by ezapartas** [comment]
Hello @maxbriel . This is the same issue that @kasdaglie pointed out in a dm, so I copy my reply there:

In step_SN, for all remnants (WD/NS/BH) we only keep a few quantities like mass, spin, etc (see line 665 in step_SN for WDs where we go in a for loop to all quantities, give a value to a few and put None to everything else). So for the WD until now we only kept its mass. For the merger process however, we kind of need to know what "layer" this mass represents, i.e. if it is total mass, he_core_mass, co_core_mass etc. In the case of WD it's total mass should be a also its co_core_mass (most WDs are  C/O WDs and a few more massive are ONeMg, but for now we cannot differentiate between them). If we add co_core_mass for WDs in step_SN, then the WD would be ready in case it merges later, and the problem should just vanish :)

**Comment by ezapartas** [comment]
This is indirectly linked with issue 31 of POSYDON-MESA-inlists, as we treat WDs as compact objects in MESA, with no info about their interior abundances etc: https://github.com/POSYDON-code/POSYDON-MESA-INLISTS/issues/31
