### ISSUE TITLE
Initial RLO in MESA output

### ISSUE THREAD

**Issue by mkruckow** [POSYDON-code/POSYDON-public#262]
Currently, when creating a PSyGrid only the last termination code stated by MESA is taken into account, this causes some runs, which experience initial RLO to be not correctly detected on PSyGrid creation.
As a consequence, they will show up as failed systems when they are at the boundary between initial RLO and RLO at MS.

In more general we need to think about how to better deal with any run, which gets more than one termination code from MESA.

**Comment by astroJeff** [comment]
@mkruckow, can you post a couple examples?

**Comment by astroJeff** [comment]
Redundant with PR #254
