### ISSUE TITLE
Trained lambda_CE is not correct for HMS-HMS grids

### ISSUE THREAD

**Issue by ZepeiX** [POSYDON-code/POSYDON-public#279]
In HMS-HMS grids, some binaries go to unstable MT but the donor stars have no envelope. These could happen when the donor is still a MS or a stripped star or more generally, partially stripped star with H abundance < what is need to define the core/envelope boundary. 
Then, the lambda_CE is set to be 1e99, which would mess up the training because all the lambda are normalized before training. The proposed fix is to set these lambda to Nan and exclude them from normalization and training.

**Comment by philipp-rajah** [comment]
@ZepeiX I am unsure how to create a criterion to exclude certain binaries from the interpolation of the lambda values. Should I exclude the binaries that are in unstable MT where the donor stars have no envelope? How do I determine whether this is true? I'm not sure which parameter indicates the envelope and the units of that parameter.

**Comment by ZepeiX** [comment]
@philipp-rajah I think this is supposed to be fixed in the PR Matthias posted above #281.
