### ISSUE TITLE
`spin_orbit_tilt` no longer an output parameter

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#283]
In the default `population_params.ini` `spin_orbit_tilt` is one of the default output options.
However with PR #129, this attribute has been removed from the SingleStar and been replaced with:
`spin_orbit_tilt_first_SN` and `spin_orbit_tilt_second_SN`

The default should be changed or `spin_orbit_tilt` option should output both.

What is the preferred behaviour here?

**Comment by maxbriel** [comment]
The naming of the attributes are also different in their initialisation compared to their where they're set?

In [SingleStar.py](https://github.com/POSYDON-code/POSYDON/blob/28c71474247747218e731622e8151a51155bf036/posydon/binary_evol/singlestar.py#L144):
```
if not hasattr(self, 'spin_orbit_tilt_first_SN'):
      self.spin_orbit_tilt_SN1 = None
if not hasattr(self, 'spin_orbit_tilt_second_SN'):
      self.spin_orbit_tilt_SN2 = None
```

In [step_SN.py](https://github.com/POSYDON-code/POSYDON/blob/28c71474247747218e731622e8151a51155bf036/posydon/binary_evol/SN/step_SN.py#L1768), one of the sets:

```
binary.star_1.spin_orbit_tilt_first_SN = tilt
binary.star_2.spin_orbit_tilt_first_SN = tilt

```

Would this be sufficient as a fix? Commit on max_synpop_population branch for: attribute names - 590e440 population_params_default.ini: 2355763

**Comment by mpgalleg** [comment]
I prefer spin_orbit_tilt option outputting both. 

We use S1, S2, CC1, CC2 etc so it is inconsistent to use first_SN and second_SN. If we can reduce that, especially in the output, that would be best I think.
