### ISSUE TITLE
BinaryStar.restore() does not reset the `step_names_history`

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#291]
When rerunning a binary I reset it, but the `step_names_history` is not reset. 

I would have expected for this to remove this history, when calling `BinaryStar.restore()` or `BinaryStar.reset()`.

**Comment by celiotine** [comment]
I think this is happening because the step_names are added with a hook class and are not part of the BINARYPROPERTIES. This should hopefully be simple to fix.

**Comment by celiotine** [comment]
[branch to fix this issue is here](https://github.com/POSYDON-code/POSYDON/tree/fix_binary_restore)
