### ISSUE TITLE
Incorrect classification/remnant masses for BHs when using interpolated values in SN step

### ISSUE THREAD

**Issue by celiotine** [POSYDON-code/POSYDON-public#303]
When running with `use_interp_values = True` in the SN settings, there is incorrect handling of some remnant masses. Specifically, these objects are either being misclassified as BHs or are assigned incorrect remnant masses. An example binary where this behavior is present is:

```
star_1 = SingleStar(**{'mass': 38.741115, 'state': 'H-rich_Core_H_burning',\
                'natal_kick_array': [21.113771, 2.060135, 2.224789, 4.089729]})
star_2 = SingleStar(**{'mass': 27.776178, 'state': 'H-rich_Core_H_burning',\
                'natal_kick_array': [282.712103, 0.296252, 1.628433, 5.623812]})

binary = BinaryStar(star_1, star_2,
                   **{'time': 0.0, 
                      'state': 'detached', 
                      'event': 'ZAMS',
                      'orbital_period': 93.387072, 
                      'eccentricity': 0.0},
                    properties = sim_prop)
```
Quest .ini file path: `/projects/b1119/cliotine/dev_general/debugging/params_Monica.ini`

This is the behavior when running with `use_interp_values = True` (S2 BH is way too low mass or is actually a NS):

<img width="652" alt="Screen Shot 2024-05-13 at 3 56 59 PM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/33fd494f-d4e0-4f4f-bb2c-cadb73c7eb57">

This is the behavior when running with `use_interp_values = False` (S2 BH looks fine):

<img width="658" alt="Screen Shot 2024-05-13 at 3 55 11 PM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/ff5b62d6-538d-4316-b05f-cf2c448b1e7b">

**Comment by mkruckow** [comment]
- Could you please add the SN_type to your two examples?
- Can you may take the state binary at the "oRLO2" for your first example to run from there with the change of the `use_interp_values` to exclude that the slight change in primary mass during its CC don't move the secondary out of the problematic regime, which might be tight.

**Comment by celiotine** [comment]
Sure, here is the evolution re-evolving from oRLO2. The outcome is similar to above:

With `use_interp_values = True`:
<img width="652" alt="Screen Shot 2024-05-17 at 10 25 38 AM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/b9eea071-296a-413a-a070-5095dfb2ddbd">

Re-evolved from oRLO2 w/ `use_interp_values = False`:
<img width="569" alt="Screen Shot 2024-05-17 at 10 26 23 AM" src="https://github.com/POSYDON-code/POSYDON/assets/13874913/9bfcdba7-97a3-46b3-9a1c-e5477d4a2d52">

The SN type for the secondary in both cases is CCSN.

**Comment by mkruckow** [comment]
OK, thanks. Do we save the interpolation class for the compact object formation? If so, is this the same as well?

**Comment by celiotine** [comment]
I cannot find a way to access the CO interpolation class from the history?

**Comment by maxbriel** [comment]
@celiotine would you be able to check if this is still an issue, once the IF interpolator fix is implemented?

**Comment by celiotine** [comment]
Yeah I can do this, will update once completed.
