### ISSUE TITLE
Clarify logic for redirecting binaries in CO-H / He HMS grids.

### ISSUE THREAD

**Issue by ka-rocha** [POSYDON-code/POSYDON-public#307]
https://github.com/POSYDON-code/POSYDON/blob/cf933e466b96ac70e9823b02ff52849585928a92/posydon/binary_evol/MESA/step_mesa.py#L1416-L1424

It is unclear what this `else` clause is doing and it is causing some binaries to go through loops where they are redirected multiple times back into the CO-HMS steps.

**Comment by maxbriel** [comment]
This code should not be there anymore. I already removed it in PR #255.

It looks like it came back in PR #287, the error checking PR.
Additionally there's code in `step_mesa.py` that was added with PR #255, which made sure to catch all the different types of out-of-grid, such that no cyclical redirects should happen.

@celiotine and @ka-rocha, this should be an easy fix. Would you be able to add the code back in and remove the part that should have been removed?
