### ISSUE TITLE
matplotlib version issues

### ISSUE THREAD

**Issue by ezapartas** [POSYDON-code/POSYDON-public#318]
Using the new posydon_v2_dev_env in quest by sourcing /projects/b1119/.bash_shared_v2_dev , I got this matplotlib error:

```
  File "/projects/b1119/POSYDON_SHARED_v2_dev/posydon/popsyn/synthetic_population.py", line 26, in <module>
    import posydon.visualization.plot_pop as plot_pop
  File "/projects/b1119/POSYDON_SHARED_v2_dev/posydon/visualization/plot_pop.py", line 19, in <module>
    cm = plt.cm.get_cmap('tab20')
         ^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```
This function got removed in matplotlib 3.9.0, hence we either need to limit the version or rewrite our code. (@mkruckow)
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#removals

**Comment by sgossage** [comment]
Just posting this for posterity:

If we decide to stay with `matplotlib` version 3.9.0 with our new v2 conda environments, we will need to change the current function call to e.g.,

```
import matplotlib as mpl
cm = mpl.colormaps.get_cmap('tab20')
```

To stay with the current function call, we should downgrade `matplotlib` to something like version 3.7.1 (which is a version used in previous environments where this call is valid).

**Comment by mkruckow** [comment]
For the moment we down graded the matplotlib version in #336 .
The way of #322 will be the better one after it got tested.

**Comment by celiotine** [comment]
PR #322 was successfully merged, so this issue should be resolved.
