### ISSUE TITLE
SN_type and CO_type not consistent

### ISSUE THREAD

**Issue by ZepeiX** [POSYDON-code/POSYDON-public#331]
I found one binary 'out of hull' and 1NN was used. But the SN_type is 'WD' and CO_type is 'NS'.
This might be a bug in the part of doing nearest neighbor. 

Initial condition:  m1 = 7.592921, m2 = 5.038679,  p = 5.537807

**Comment by celiotine** [comment]
This is related to Issue #280, so I will close this one for now and add comment there.
