### ISSUE TITLE
IF interpolation all NaN slices

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#341]
@ZepeiX showed that lambda values for grid slices in the CO_HeMS(_RLO) grid have lambda values ( ie `S1_lambda_CE_pure_He_star_1cent`) that are **all** NaN. PR #338 still has NaN slices in training.

**Current behaviour:**
As such, these parameters are not included in the `BaseIFInterpolator.evaluate()` output. This function returns interpolator values from `out_keys` and `out_nan_keys` stored in the BaseIFInterpolator.
Because we set `out_keys` as an input based on the presence of at least 1 non-nan value in the grid, the key is excluded and`out_nan_keys` is not calculated, since it's not part of `BaseIFInterpolator.__init__`.

**Expected behaviour**
We want the interpolator to return these grid values to allow for CE evolution.
As such, I've added the `out_nan_keys` as an input to the `BaseIFInterpolator.__init__` in PR #342

**Comment by celiotine** [comment]
This should have been resolved with PR #342
