### ISSUE TITLE
get_redshift_from_cosmic_time doe not work

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#378]
The `get_redshift_from_cosmic_time(t_cosm)` function calls `redshift_from_cosmic_time_interpolator(t_cosm)`

However, `redshift_from_cosmic_time_interpolator` does not take a function input. It returns the interpolator itself.
The `get_redshift_from_cosmic_time` function should be altered.

**Comment by celiotine** [comment]
Branch created from development called "fix_redshift_cosmic_time"

**Comment by celiotine** [comment]
See PR #381
