### ISSUE TITLE
Classification Errors

### ISSUE THREAD

**Issue by philipp-rajah** [POSYDON-code/POSYDON-public#41]
S1_direct_state, S1_Fryer+12-rapid_state, S1_Fryer+12-delayed_state, S1_Sukhbold+16-engineN20_state, and S1_Patton&Sukhbold20-engineN20_state all fail to classify any White Dwarves correctly which may be causing interpolation errors.

**Comment by astroJeff** [comment]
@prinse1545, do you know if this is still a problem?

**Comment by ssbvr** [comment]
The white dwarf (WD) label was not exported correctly. This issue should be fixed by now, when we did the move to the new nomenclature `S1_MODELXX_CO_type`.
