### ISSUE TITLE
path MESA column list -- submission script

### ISSUE THREAD

**Issue by ssbvr** [POSYDON-code/POSYDON-public#47]
I am reporting here something that might be an issue for people when running MESA grids. The `posydon-setup-grid` script clones the inlists submodule in the home directory of the user. Then, it does the layering of the inlists in the working directory which are copied over in the simulation directory once the job starts. However, the files `binary_history_columns.list`, `history_columns.list` and `profile_columns.list` are copied to the job directory from the cloned inlist submodule and not from the working directory. If someone deletes such a directory or runs a different version of the files, it will mess up the previously submitted simulations. Seth run again such a problem last week.

**Comment by astroJeff** [comment]
From a brief glance at the code, @ssbvr, this looks fixed. Can you confirm?

**Comment by ssbvr** [comment]
I think this issue was never fixed.
