### ISSUE TITLE
NaN values for "merged", "initial_RLO" times

### ISSUE THREAD

**Issue by celiotine** [POSYDON-code/POSYDON-public#56]
Currently, the "time" values for the "merged" and "initial_RLO" states are designated with NaN. This is confusing for users because other states where the binary no longer exists (e.g. "disrupted") do not do this. This also creates minor issues with post-processing in pandas. These NaNs should be replaced with something else (e.g. time at merger or initial RLO). Also check if this happens for any other states.

**Comment by astroJeff** [comment]
This is now resolved.
