### ISSUE TITLE
Incompatible SN type and compact object state

### ISSUE THREAD

**Issue by astro-abhishek** [POSYDON-code/POSYDON-public#79]
The SN type and compact object state are not consistent with each other in some cases. This is because, right now, the two are being classified independently with no further compatibility checks. One solution proposed by Simone, is to overwrite the SN type to make it agree with the classified compact object state in case there's a conflict. 

Below is one such example of a NS with the SN type as WD (and therefore, no natal kick values). In this case, the SN type should be "sanitized" from WD to ECSN.

![Screenshot 2023-05-18 at 4 19 58 PM](https://github.com/POSYDON-code/POSYDON/assets/40901312/4cacadef-b4da-438c-a8fd-66ad1be4193d)

**Comment by astroJeff** [comment]
This issue appears to be fixed with PR #240, tested by @astro-abhishek
