### ISSUE TITLE
Introduce a step_CO-HeMS_RLO

### ISSUE THREAD

**Issue by ssbvr** [POSYDON-code/POSYDON-public#81]
Massive binaries in the high metallicity HMS-HMS grids can reach carbon depletion of the primary star, with the secondary star being stripped. In these binaries, stellar winds are strong enough to strip the secondary star completely before the primary collapses to form the firstborn BH. The core collapses my imparts a kick to the binary system leading to an eccentric DCO-stripped-He star. These binary systems are currently incorrectly mapped to the step_CO-HeMS, where eccentricity is ignored. In reality, we should map these systems to the detached step, and if RLO is encountered, map them to a step_CO-HeMS_RLO.

**Comment by mkruckow** [comment]
Done in [PR#122](https://github.com/POSYDON-code/POSYDON/pull/122)
